apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-this-in-production"
  DB_PASSWORD: "arkheion_pass"
  GOOGLE_OAUTH2_CLIENT_ID: "2756xxxxx.apps.googleusercontent.com"
  GOOGLE_OAUTH2_CLIENT_SECRET: "sua_chave_aqui"
  GOOGLE_OAUTH2_REDIRECT_URI: "http://localhost:5173/auth/google/callback"
