# Generated by Django 5.1.5 on 2025-02-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ataque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Ataque"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Ataque")),
                ("dano", models.CharField(max_length=200, verbose_name="Dano")),
                (
                    "tipo_dano",
                    models.CharField(
                        choices=[
                            ("imp", "Impacto"),
                            ("per", "Perfuração"),
                            ("cor", "Corte"),
                            ("men", "Mental"),
                            ("acd", "Ácido"),
                            ("ele", "Eletricidade"),
                            ("esc", "Essência"),
                            ("fog", "Fogo"),
                            ("fri", "Frio"),
                            ("luz", "Luz"),
                            ("tre", "Trevas"),
                            ("ven", "Veneno"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Dano",
                    ),
                ),
                (
                    "resistencia",
                    models.CharField(
                        default="---", max_length=200, verbose_name="Resistencia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("for", "Força"),
                            ("des", "Destreza"),
                            ("con", "Constituição"),
                            ("int", "Inteligência"),
                            ("sab", "Sabedoria"),
                            ("car", "Carisma"),
                        ],
                        max_length=3,
                        verbose_name="Atributo",
                    ),
                ),
                ("ordem", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição de Classe"
                    ),
                ),
                ("proficiencia", models.TextField(verbose_name="Proficiências")),
                ("vida_base", models.IntegerField(default=0, verbose_name="Vida base")),
                (
                    "vida_por_nivel",
                    models.IntegerField(default=0, verbose_name="Vida por nivel"),
                ),
                ("mana_base", models.IntegerField(default=0, verbose_name="Mana base")),
                (
                    "mana_por_nivel",
                    models.IntegerField(default=0, verbose_name="Mana por nivel"),
                ),
                (
                    "pericias_treinadas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perícias Treinadas"
                    ),
                ),
                (
                    "pericias_para_escolher",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perícias para escolher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(verbose_name="Descrição do Habilidade")),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("rc", "Raça"),
                            ("or", "Origem"),
                            ("cl", "Classe"),
                            ("ge", "Geral"),
                            ("de", "Destino"),
                            ("to", "Tormenta"),
                            ("ou", "Outro"),
                        ],
                        max_length=2,
                    ),
                ),
                ("ativo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Origem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição de Origem"
                    ),
                ),
                (
                    "poderes_concedidos_origem",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Poderes Concedidos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pericia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("acr", "Acrobacia"),
                            ("ade", "Adestramento"),
                            ("atl", "Atletismo"),
                            ("atu", "Atuação"),
                            ("cav", "Cavalgar"),
                            ("con", "Conhecimento"),
                            ("cur", "Cura"),
                            ("dip", "Diplomacia"),
                            ("eng", "Enganação"),
                            ("for", "Fortitude"),
                            ("fur", "Furtividade"),
                            ("gue", "Guerra"),
                            ("ini", "Iniciativa"),
                            ("int", "Intimidação"),
                            ("inu", "Intuição"),
                            ("inv", "Investigação"),
                            ("jog", "Jogatina"),
                            ("lad", "Ladinagem"),
                            ("lut", "Luta"),
                            ("mis", "Misticismo"),
                            ("nob", "Nobreza"),
                            ("ofi", "Ofício"),
                            ("per", "Percepção"),
                            ("pil", "Pilotagem"),
                            ("pon", "Pontaria"),
                            ("ref", "Reflexos"),
                            ("rel", "Religião"),
                            ("sob", "Sobrevivência"),
                            ("von", "Vontade"),
                        ],
                        max_length=3,
                        verbose_name="Perícia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição de Raça"
                    ),
                ),
                (
                    "poderes_concedidos_raca",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Poderes Concedidos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("senha", models.CharField(max_length=200, verbose_name="Senha")),
            ],
        ),
        migrations.CreateModel(
            name="AtributoFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(max_length=200, verbose_name="Valor")),
                (
                    "atributo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ficha.atributo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ficha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("nivel", models.IntegerField(default=0, verbose_name="Nível")),
                (
                    "divindade",
                    models.CharField(max_length=200, verbose_name="divindade"),
                ),
                (
                    "cd",
                    models.CharField(
                        max_length=200, verbose_name="Classe de Dificuldade de Magias"
                    ),
                ),
                (
                    "ca",
                    models.CharField(max_length=200, verbose_name="Classe de Armadura"),
                ),
                (
                    "vida_atual",
                    models.IntegerField(default=0, verbose_name="Vida Atual"),
                ),
                (
                    "vida_max",
                    models.IntegerField(default=0, verbose_name="Vida Máxima"),
                ),
                (
                    "mana_atual",
                    models.IntegerField(default=0, verbose_name="Mana Atual"),
                ),
                (
                    "mana_max",
                    models.IntegerField(default=0, verbose_name="Mana Máxima"),
                ),
                ("exp", models.IntegerField(default=0, verbose_name="Experiência")),
                ("ataques", models.ManyToManyField(to="ficha.ataque")),
                (
                    "atributos",
                    models.ManyToManyField(
                        through="ficha.AtributoFicha", to="ficha.atributo"
                    ),
                ),
                ("habilidades", models.ManyToManyField(to="ficha.habilidade")),
            ],
        ),
        migrations.AddField(
            model_name="atributoficha",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ficha.ficha",
            ),
        ),
        migrations.CreateModel(
            name="NivelClasseFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.IntegerField(default=1, verbose_name="Nivel")),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ficha.classe",
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ficha.ficha",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ficha",
            name="classes",
            field=models.ManyToManyField(
                related_name="classeFicha",
                through="ficha.NivelClasseFicha",
                to="ficha.classe",
            ),
        ),
        migrations.CreateModel(
            name="NivelHabilidadeClasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_da_habilidade",
                    models.IntegerField(default=1, verbose_name="Nível"),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ficha.classe",
                    ),
                ),
                (
                    "habilidades",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ficha.habilidade",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classe",
            name="habilidades_por_nivel",
            field=models.ManyToManyField(
                related_name="habilidadesPorNivel",
                through="ficha.NivelHabilidadeClasse",
                to="ficha.habilidade",
            ),
        ),
        migrations.AddField(
            model_name="habilidade",
            name="origem_pers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.origem",
            ),
        ),
        migrations.AddField(
            model_name="ficha",
            name="origens",
            field=models.ManyToManyField(to="ficha.origem"),
        ),
        migrations.AddField(
            model_name="ataque",
            name="pericia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ficha.pericia",
            ),
        ),
        migrations.CreateModel(
            name="PericiaTreinada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treinado",
                    models.BooleanField(default=False, verbose_name="Treinado"),
                ),
                (
                    "atributo_chave",
                    models.ManyToManyField(
                        related_name="atributoChave",
                        to="ficha.atributoficha",
                        verbose_name="Atributo Chave",
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ficha.ficha",
                    ),
                ),
                (
                    "pericia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ficha.pericia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ficha",
            name="pericias",
            field=models.ManyToManyField(
                related_name="periciaTreinada",
                through="ficha.PericiaTreinada",
                to="ficha.pericia",
            ),
        ),
        migrations.AddField(
            model_name="habilidade",
            name="raca_pers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.raca",
            ),
        ),
        migrations.AddField(
            model_name="ficha",
            name="racas",
            field=models.ManyToManyField(to="ficha.raca"),
        ),
        migrations.AddField(
            model_name="ficha",
            name="dono",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.usuario",
            ),
        ),
    ]
