# Generated by Django 5.1.5 on 2025-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atributoficha",
            name="valor",
            field=models.IntegerField(verbose_name="Valor"),
        ),
    ]
