# Generated by Django 5.1.5 on 2025-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0002_alter_atributoficha_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="pericia",
            name="requer_treino",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Requer treino?"
            ),
        ),
    ]
