# Generated by Django 5.1.6 on 2025-02-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0003_pericia_requer_treino"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ficha",
            name="divindade",
            field=models.CharField(
                choices=[
                    ("NO", "Nenhuma"),
                    ("AH", "Aharadak, Deus da Tormenta"),
                    ("AL", "Allihanna, Deusa da Natureza"),
                    ("AR", "Arsenal, Deus da Guerra"),
                    ("AZ", "Azgher, Deus do Sol"),
                    ("HY", "Hyninn, Deus da Trapaça"),
                    ("KA", "Kallyadranoch, Deus dos Dragões"),
                    ("KH", "Khalmyr, Deus da Justiça"),
                    ("LE", "Lena, Deusa da Vida"),
                    ("LI", "Lin-Wu, Deus da Honra"),
                    ("MA", "Marah, Deusa da Paz"),
                    ("ME", "Megalokk, Deus dos Monstros"),
                    ("NI", "Nimb, Deus do Caos"),
                    ("OC", "Oceano, Deus do Oceano"),
                    ("SS", "Sszzaas, Deus da Traição"),
                    ("TA", "Tanna-Toh, Deusa do Conhecimento"),
                    ("TE", "Tenebra, Deusa da Noite"),
                    ("TH", "Thwor, Deus dos Goblinóides"),
                    ("TY", "Thyatis, Deus da Ressurreição"),
                    ("VA", "Valkaria, Deusa da Ambição"),
                    ("WY", "Wynna, Deusa da Magia"),
                ],
                max_length=2,
                verbose_name="Divindade",
            ),
        ),
        migrations.AlterField(
            model_name="pericia",
            name="requer_treino",
            field=models.BooleanField(default=False, verbose_name="Requer treino?"),
        ),
    ]
