# Generated by Django 5.1.6 on 2025-02-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0004_alter_ficha_divindade_alter_pericia_requer_treino"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classe",
            name="habilidades_por_nivel",
        ),
        migrations.AddField(
            model_name="habilidade",
            name="classe_pers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="ficha.classe",
                verbose_name="Classe de origem",
            ),
        ),
        migrations.AddField(
            model_name="habilidade",
            name="nivel_habilidade",
            field=models.IntegerField(default=0, verbose_name="Nível da Habilidade"),
        ),
        migrations.AlterField(
            model_name="habilidade",
            name="origem_pers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.origem",
                verbose_name="Origem de origem",
            ),
        ),
        migrations.AlterField(
            model_name="habilidade",
            name="raca_pers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.raca",
                verbose_name="Raça de origem",
            ),
        ),
        migrations.DeleteModel(
            name="NivelHabilidadeClasse",
        ),
    ]
