# Generated by Django 5.1.6 on 2025-02-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0005_remove_classe_habilidades_por_nivel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habilidade",
            name="classe_pers",
        ),
        migrations.AddField(
            model_name="habilidade",
            name="classe_pers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.classe",
                verbose_name="Classe de origem",
            ),
        ),
    ]
