# Generated by Django 5.1.6 on 2025-02-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0006_remove_habilidade_classe_pers_habilidade_classe_pers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ficha",
            name="mana_max",
        ),
        migrations.RemoveField(
            model_name="ficha",
            name="vida_max",
        ),
    ]
