# Generated by Django 5.1.6 on 2025-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0006_remove_habilidade_classe_pers_habilidade_classe_pers"),
    ]

    operations = [
        migrations.AddField(
            model_name="periciatreinada",
            name="deslocamento",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Deslocamento"
            ),
        ),
        migrations.AddField(
            model_name="periciatreinada",
            name="tamanho",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Tamanho"
            ),
        ),
    ]
