# Generated by Django 5.1.6 on 2025-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0007_periciatreinada_deslocamento_periciatreinada_tamanho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periciatreinada",
            name="deslocamento",
        ),
        migrations.RemoveField(
            model_name="periciatreinada",
            name="tamanho",
        ),
        migrations.AddField(
            model_name="ficha",
            name="deslocamento",
            field=models.CharField(
                default="9 metros/ 6 quadrados",
                max_length=50,
                verbose_name="Deslocamento",
            ),
        ),
        migrations.AddField(
            model_name="ficha",
            name="tamanho",
            field=models.CharField(
                default="Médio", max_length=50, verbose_name="Tamanho"
            ),
        ),
        migrations.AlterField(
            model_name="ficha",
            name="ca",
            field=models.CharField(
                default="10", max_length=200, verbose_name="Classe de Armadura"
            ),
        ),
        migrations.AlterField(
            model_name="ficha",
            name="cd",
            field=models.CharField(
                default="10",
                max_length=200,
                verbose_name="Classe de Dificuldade de Magias",
            ),
        ),
    ]
