# Generated by Django 5.1.6 on 2025-02-19 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0007_remove_ficha_mana_max_remove_ficha_vida_max"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atributoficha",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.ficha",
            ),
        ),
        migrations.AlterField(
            model_name="periciatreinada",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ficha.ficha",
            ),
        ),
    ]
