# Generated by Django 5.1.6 on 2025-02-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0008_alter_atributoficha_ficha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="periciatreinada",
            name="bonus_pericia",
            field=models.IntegerField(default=0),
        ),
    ]
