# Generated by Django 5.1.6 on 2025-02-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0009_periciatreinada_bonus_pericia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="periciatreinada",
            old_name="bonus_pericia",
            new_name="bonus_treino",
        ),
    ]
