# Generated by Django 5.1.6 on 2025-02-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0010_rename_bonus_pericia_periciatreinada_bonus_treino"),
    ]

    operations = [
        migrations.RenameField(
            model_name="periciatreinada",
            old_name="bonus_treino",
            new_name="bonus_adicional",
        ),
    ]
