# Generated by Django 4.0.6 on 2025-02-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0008_remove_periciatreinada_deslocamento_and_more"),
        ("ficha", "0011_rename_bonus_treino_periciatreinada_bonus_adicional"),
    ]

    operations = []
