# Generated by Django 4.0.6 on 2025-02-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0012_merge_20250222_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periciatreinada",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ficha.ficha",
            ),
        ),
    ]
