# Generated by Django 5.1.6 on 2025-02-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0014_alter_ficha_dono"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
