# Generated by Django 5.1.5 on 2025-06-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ataque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Ataque"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Ataque")),
                ("dano", models.CharField(max_length=200, verbose_name="Dano")),
                (
                    "tipo_dano",
                    models.CharField(
                        choices=[
                            ("imp", "Impacto"),
                            ("per", "Perfuração"),
                            ("cor", "Corte"),
                            ("men", "Mental"),
                            ("acd", "Ácido"),
                            ("ele", "Eletricidade"),
                            ("esc", "Essência"),
                            ("fog", "Fogo"),
                            ("fri", "Frio"),
                            ("luz", "Luz"),
                            ("tre", "Trevas"),
                            ("ven", "Veneno"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Dano",
                    ),
                ),
                (
                    "resistencia",
                    models.CharField(
                        default="---", max_length=200, verbose_name="Resistencia"
                    ),
                ),
                (
                    "homebrew",
                    models.BooleanField(default=False, verbose_name="Homebrew?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("for", "Força"),
                            ("des", "Destreza"),
                            ("con", "Constituição"),
                            ("int", "Inteligência"),
                            ("sab", "Sabedoria"),
                            ("car", "Carisma"),
                        ],
                        max_length=3,
                        verbose_name="Atributo",
                    ),
                ),
                ("ordem", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição de Classe"
                    ),
                ),
                ("proficiencia", models.TextField(verbose_name="Proficiências")),
                ("vida_base", models.IntegerField(default=0, verbose_name="Vida base")),
                (
                    "vida_por_nivel",
                    models.IntegerField(default=0, verbose_name="Vida por nivel"),
                ),
                ("mana_base", models.IntegerField(default=0, verbose_name="Mana base")),
                (
                    "mana_por_nivel",
                    models.IntegerField(default=0, verbose_name="Mana por nivel"),
                ),
                (
                    "pericias_treinadas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perícias Treinadas"
                    ),
                ),
                (
                    "pericias_para_escolher",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perícias para escolher"
                    ),
                ),
                (
                    "homebrew",
                    models.BooleanField(default=False, verbose_name="Homebrew?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Divindade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Divindade"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da Divindade"
                    ),
                ),
                (
                    "simbolo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Símbolo da Divindade",
                    ),
                ),
                (
                    "obrigacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Obrigações da Divindade"
                    ),
                ),
                (
                    "restrições",
                    models.TextField(
                        blank=True, null=True, verbose_name="Restrições da Divindade"
                    ),
                ),
                (
                    "homebrew",
                    models.BooleanField(default=False, verbose_name="Homebrew?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Origem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição de Origem"
                    ),
                ),
                (
                    "homebrew",
                    models.BooleanField(default=False, verbose_name="Homebrew?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pericia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("acr", "Acrobacia"),
                            ("ade", "Adestramento"),
                            ("atl", "Atletismo"),
                            ("atu", "Atuação"),
                            ("cav", "Cavalgar"),
                            ("con", "Conhecimento"),
                            ("cur", "Cura"),
                            ("dip", "Diplomacia"),
                            ("eng", "Enganação"),
                            ("for", "Fortitude"),
                            ("fur", "Furtividade"),
                            ("gue", "Guerra"),
                            ("ini", "Iniciativa"),
                            ("int", "Intimidação"),
                            ("inu", "Intuição"),
                            ("inv", "Investigação"),
                            ("jog", "Jogatina"),
                            ("lad", "Ladinagem"),
                            ("lut", "Luta"),
                            ("mis", "Misticismo"),
                            ("nob", "Nobreza"),
                            ("ofi", "Ofício"),
                            ("per", "Percepção"),
                            ("pil", "Pilotagem"),
                            ("pon", "Pontaria"),
                            ("ref", "Reflexos"),
                            ("rel", "Religião"),
                            ("sob", "Sobrevivência"),
                            ("von", "Vontade"),
                        ],
                        max_length=3,
                        verbose_name="Perícia",
                    ),
                ),
                (
                    "requer_treino",
                    models.BooleanField(default=False, verbose_name="Requer treino?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição de Raça"
                    ),
                ),
                (
                    "homebrew",
                    models.BooleanField(default=False, verbose_name="Homebrew?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtributoFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.IntegerField(verbose_name="Valor")),
                (
                    "atributo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.atributo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtributoMonstro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.IntegerField(verbose_name="Valor")),
                (
                    "atributo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.atributo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ficha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("nivel", models.IntegerField(default=0, verbose_name="Nível")),
                (
                    "cd",
                    models.CharField(
                        default="10",
                        max_length=200,
                        verbose_name="Classe de Dificuldade de Magias",
                    ),
                ),
                (
                    "ca",
                    models.CharField(
                        default="10", max_length=200, verbose_name="Classe de Armadura"
                    ),
                ),
                (
                    "vida_atual",
                    models.IntegerField(default=0, verbose_name="Vida Atual"),
                ),
                (
                    "mana_atual",
                    models.IntegerField(default=0, verbose_name="Mana Atual"),
                ),
                ("exp", models.IntegerField(default=0, verbose_name="Experiência")),
                (
                    "deslocamento",
                    models.CharField(
                        default="9 metros/ 6 quadrados",
                        max_length=50,
                        verbose_name="Deslocamento",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        default="Médio", max_length=50, verbose_name="Tamanho"
                    ),
                ),
                ("ataques", models.ManyToManyField(to="backend.ataque")),
                (
                    "atributos",
                    models.ManyToManyField(
                        through="backend.AtributoFicha", to="backend.atributo"
                    ),
                ),
                (
                    "divindade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="divindade_ficha",
                        to="backend.divindade",
                        verbose_name="Divindade",
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="atributoficha",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.ficha",
            ),
        ),
        migrations.CreateModel(
            name="Habilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(verbose_name="Descrição do Habilidade")),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("rc", "Raça"),
                            ("or", "Origem"),
                            ("cl", "Classe"),
                            ("ge", "Geral"),
                            ("de", "Destino"),
                            ("to", "Tormenta"),
                            ("ou", "Outro"),
                        ],
                        max_length=2,
                    ),
                ),
                ("ativo", models.BooleanField(default=False)),
                (
                    "nivel_habilidade",
                    models.IntegerField(default=0, verbose_name="Nível da Habilidade"),
                ),
                (
                    "homebrew",
                    models.BooleanField(default=False, verbose_name="Homebrew?"),
                ),
                (
                    "classe_pers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.classe",
                        verbose_name="Classe de origem",
                    ),
                ),
                (
                    "divindade_pers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.divindade",
                        verbose_name="Divindade de origem",
                    ),
                ),
                (
                    "origem_pers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.origem",
                        verbose_name="Origem de origem",
                    ),
                ),
                (
                    "raca_pers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.raca",
                        verbose_name="Raça de origem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ficha",
            name="habilidades",
            field=models.ManyToManyField(to="backend.habilidade"),
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome da Mesa")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da Mesa"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MesaParticipante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("J", "Jogador"),
                            ("M", "Mestre"),
                            ("O", "Observador"),
                        ],
                        default="Jogador",
                        max_length=1,
                        verbose_name="Tipo de Participante",
                    ),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Entrada"
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Saída"
                    ),
                ),
                (
                    "iniciativa",
                    models.IntegerField(default=0, verbose_name="Iniciativa"),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mesa_ficha",
                        to="backend.ficha",
                    ),
                ),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesa_jogador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesa_jogador",
                        to="backend.mesa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mesa",
            name="participante",
            field=models.ManyToManyField(
                related_name="mesa_participante",
                through="backend.MesaParticipante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Monstro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("nivel", models.IntegerField(default=0, verbose_name="Nível")),
                (
                    "nd",
                    models.IntegerField(default=0, verbose_name="Nível de Dificuldade"),
                ),
                (
                    "cd",
                    models.CharField(
                        blank=True,
                        default="10",
                        max_length=200,
                        null=True,
                        verbose_name="Classe de Dificuldade de Magias",
                    ),
                ),
                (
                    "ca",
                    models.CharField(
                        blank=True,
                        default="10",
                        max_length=200,
                        null=True,
                        verbose_name="Classe de Armadura",
                    ),
                ),
                ("vida", models.IntegerField(default=0, verbose_name="Vida Atual")),
                ("mana", models.IntegerField(default=0, verbose_name="Mana Atual")),
                (
                    "deslocamento",
                    models.CharField(
                        default="9 metros/ 6 quadrados",
                        max_length=50,
                        verbose_name="Deslocamento",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        default="Médio", max_length=50, verbose_name="Tamanho"
                    ),
                ),
                ("ataques", models.ManyToManyField(to="backend.ataque")),
                (
                    "atributos",
                    models.ManyToManyField(
                        through="backend.AtributoMonstro", to="backend.atributo"
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("habilidades", models.ManyToManyField(to="backend.habilidade")),
            ],
        ),
        migrations.CreateModel(
            name="MesaCombate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno_atual",
                    models.IntegerField(default=0, verbose_name="Turno Atual"),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesa_combate",
                        to="backend.mesa",
                    ),
                ),
                (
                    "monstros",
                    models.ManyToManyField(
                        blank=True,
                        related_name="monstros_da_mesa",
                        to="backend.monstro",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="atributomonstro",
            name="monstro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.monstro",
            ),
        ),
        migrations.CreateModel(
            name="NivelClasseFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.IntegerField(default=1, verbose_name="Nivel")),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.classe",
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.ficha",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ficha",
            name="classes",
            field=models.ManyToManyField(
                related_name="classeFicha",
                through="backend.NivelClasseFicha",
                to="backend.classe",
            ),
        ),
        migrations.AddField(
            model_name="ficha",
            name="origens",
            field=models.ManyToManyField(to="backend.origem"),
        ),
        migrations.CreateModel(
            name="MonstroPericia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atributo_chave",
                    models.ManyToManyField(
                        related_name="atributoChaveMonstro",
                        to="backend.atributomonstro",
                        verbose_name="Atributo Chave",
                    ),
                ),
                (
                    "monstro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.monstro",
                    ),
                ),
                (
                    "pericia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.pericia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="monstro",
            name="pericias",
            field=models.ManyToManyField(
                related_name="monstroPericia",
                through="backend.MonstroPericia",
                to="backend.pericia",
            ),
        ),
        migrations.AddField(
            model_name="ataque",
            name="pericia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.pericia",
            ),
        ),
        migrations.CreateModel(
            name="PericiaTreinada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treinado",
                    models.BooleanField(default=False, verbose_name="Treinado"),
                ),
                ("bonus_adicional", models.IntegerField(default=0)),
                (
                    "atributo_chave",
                    models.ManyToManyField(
                        related_name="atributoChave",
                        to="backend.atributoficha",
                        verbose_name="Atributo Chave",
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.ficha",
                    ),
                ),
                (
                    "pericia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.pericia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ficha",
            name="pericias",
            field=models.ManyToManyField(
                related_name="periciaTreinada",
                through="backend.PericiaTreinada",
                to="backend.pericia",
            ),
        ),
        migrations.AddField(
            model_name="ficha",
            name="racas",
            field=models.ManyToManyField(to="backend.raca"),
        ),
    ]
