# Generated by Django 5.2.1 on 2025-10-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome do Item")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor (T$)",
                    ),
                ),
                (
                    "eh_kit",
                    models.BooleanField(default=False, verbose_name="É um Kit?"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("arma", "Arma"),
                            ("armadura", "Armadura"),
                            ("acessorio", "Acessório"),
                            ("pocao", "Poção"),
                            ("material", "Material"),
                            ("kit", "Kit"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemkit_filho",
                        to="backend.item",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemkit_pai",
                        to="backend.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Kit",
                "verbose_name_plural": "Itens do Kit",
                "unique_together": {("kit", "item")},
            },
        ),
        migrations.AddField(
            model_name="item",
            name="itens_do_kit",
            field=models.ManyToManyField(
                blank=True, through="backend.ItemKit", to="backend.item"
            ),
        ),
        migrations.CreateModel(
            name="InventarioFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "equipado",
                    models.BooleanField(default=False, verbose_name="Equipado?"),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="backend.ficha",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Inventário",
                "verbose_name_plural": "Itens do Inventário",
                "unique_together": {("ficha", "item")},
            },
        ),
    ]
